// 追加の部品の目次。parts/ の 1 部品 1 ファイルをここに並べる（xsasm-parts.js が読む）
import vfin from './vfin.js';
import headband from './headband.js';
import collar from './collar.js';
import maska from './maska.js';
import china from './china.js';
import finplate from './finplate.js';
import horn from './horn.js';
import antenna from './antenna.js';
import visorhelm from './visorhelm.js';
import boxhelm from './boxhelm.js';
import earblock from './earblock.js';
import chinguard from './chinguard.js';
import neck from './neck.js';
import monoeye from './monoeye.js';
import twineyes from './twineyes.js';
import backfin from './backfin.js';
import thruster from './thruster.js';
import cheekguard from './cheekguard.js';
export const EXTRA = [vfin, headband, collar, maska, china, finplate, horn, antenna, visorhelm, boxhelm, earblock, chinguard, neck, monoeye, twineyes, backfin, thruster, cheekguard].flat();
